In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ds = pd.read_csv("books.csv")
ds

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,6,11870085,11870085,16827462,226,525478817,9.780525e+12,John Green,2012.0,The Fault in Our Stars,...,2346404,2478609,140739,47994,92723,327550,698471,1311871,https://images.gr-assets.com/books/1360206420m...,https://images.gr-assets.com/books/1360206420s...
4,12,13335037,13335037,13155899,210,62024035,9.780062e+12,Veronica Roth,2011.0,Divergent,...,1903563,2216814,101023,36315,82870,310297,673028,1114304,https://images.gr-assets.com/books/1328559506m...,https://images.gr-assets.com/books/1328559506s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,9925,86737,86737,3877968,52,1582349177,9.781582e+12,Mary Hoffman,2002.0,City of Masks,...,12048,13385,555,314,758,3154,4872,4287,https://images.gr-assets.com/books/1294870497m...,https://images.gr-assets.com/books/1294870497s...
1350,9937,13010211,13010211,18171867,22,1596435712,9.781596e+12,Caragh M. O'Brien,2012.0,Promised,...,11766,12884,1260,256,1098,3565,4392,3573,https://images.gr-assets.com/books/1330546217m...,https://images.gr-assets.com/books/1330546217s...
1351,9942,16074758,16074758,21869436,18,1442486597,9.781442e+12,"Abigail Haas, Abby McDonald",2013.0,Dangerous Girls,...,10439,12970,2631,203,553,2029,4567,5618,https://images.gr-assets.com/books/1356513050m...,https://images.gr-assets.com/books/1356513050s...
1352,9947,21393526,21393526,40690062,19,62320521,9.780062e+12,Maria Dahvana Headley,2015.0,Magonia,...,12510,13652,2910,577,1440,3881,4772,2982,https://images.gr-assets.com/books/1413479866m...,https://images.gr-assets.com/books/1413479866s...
1353,9955,13065327,13065327,18230950,25,802734375,9.780803e+12,Simone Elkeles,2013.0,Wild Cards,...,13954,15400,1514,406,965,3331,5038,5660,https://images.gr-assets.com/books/1420836321m...,https://images.gr-assets.com/books/1420836321s...

In [4]:
ds.columns

Index(['book_id', 'goodreads_book_id', 'best_book_id', 'work_id',
       'books_count', 'isbn', 'isbn13', 'authors', 'original_publication_year',
       'original_title', 'title', 'language_code', 'average_rating',
       'ratings_count', 'work_ratings_count', 'work_text_reviews_count',
       'ratings_1', 'ratings_2', 'ratings_3', 'ratings_4', 'ratings_5',
       'image_url', 'small_image_url'],
      dtype='object')

In [3]:
null_values = ds.isnull().sum()

# Display the number of null values
null_values

book_id                        0
goodreads_book_id              0
best_book_id                   0
work_id                        0
books_count                    0
isbn                          52
isbn13                        44
authors                        0
original_publication_year      3
original_title                52
title                          0
language_code                109
average_rating                 0
ratings_count                  0
work_ratings_count             0
work_text_reviews_count        0
ratings_1                      0
ratings_2                      0
ratings_3                      0
ratings_4                      0
ratings_5                      0
image_url                      0
small_image_url                0
dtype: int64

In [5]:
cleaned_ds = ds.dropna()

In [6]:
cleaned_ds

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,6,11870085,11870085,16827462,226,525478817,9.780525e+12,John Green,2012.0,The Fault in Our Stars,...,2346404,2478609,140739,47994,92723,327550,698471,1311871,https://images.gr-assets.com/books/1360206420m...,https://images.gr-assets.com/books/1360206420s...
4,12,13335037,13335037,13155899,210,62024035,9.780062e+12,Veronica Roth,2011.0,Divergent,...,1903563,2216814,101023,36315,82870,310297,673028,1114304,https://images.gr-assets.com/books/1328559506m...,https://images.gr-assets.com/books/1328559506s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,9925,86737,86737,3877968,52,1582349177,9.781582e+12,Mary Hoffman,2002.0,City of Masks,...,12048,13385,555,314,758,3154,4872,4287,https://images.gr-assets.com/books/1294870497m...,https://images.gr-assets.com/books/1294870497s...
1350,9937,13010211,13010211,18171867,22,1596435712,9.781596e+12,Caragh M. O'Brien,2012.0,Promised,...,11766,12884,1260,256,1098,3565,4392,3573,https://images.gr-assets.com/books/1330546217m...,https://images.gr-assets.com/books/1330546217s...
1351,9942,16074758,16074758,21869436,18,1442486597,9.781442e+12,"Abigail Haas, Abby McDonald",2013.0,Dangerous Girls,...,10439,12970,2631,203,553,2029,4567,5618,https://images.gr-assets.com/books/1356513050m...,https://images.gr-assets.com/books/1356513050s...
1352,9947,21393526,21393526,40690062,19,62320521,9.780062e+12,Maria Dahvana Headley,2015.0,Magonia,...,12510,13652,2910,577,1440,3881,4772,2982,https://images.gr-assets.com/books/1413479866m...,https://images.gr-assets.com/books/1413479866s...
1353,9955,13065327,13065327,18230950,25,802734375,9.780803e+12,Simone Elkeles,2013.0,Wild Cards,...,13954,15400,1514,406,965,3331,5038,5660,https://images.gr-assets.com/books/1420836321m...,https://images.gr-assets.com/books/1420836321s...

In [7]:
null_values = cleaned_ds.isnull().sum()
null_values

book_id                      0
goodreads_book_id            0
best_book_id                 0
work_id                      0
books_count                  0
isbn                         0
isbn13                       0
authors                      0
original_publication_year    0
original_title               0
title                        0
language_code                0
average_rating               0
ratings_count                0
work_ratings_count           0
work_text_reviews_count      0
ratings_1                    0
ratings_2                    0
ratings_3                    0
ratings_4                    0
ratings_5                    0
image_url                    0
small_image_url              0
dtype: int64

In [ ]:
cleaned_ds.drop(columns=['small_image_url', 'image_url', 'original_title', 'book_id','goodreads_book_id','best_book_id','work_id','isbn','isbn13'], inplace=True)

In [10]:
cleaned_ds

,books_count,authors,original_publication_year,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
0,272,Suzanne Collins,2008.0,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317
1,491,"J.K. Rowling, Mary GrandPr√©",1997.0,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543
2,226,Stephenie Meyer,2005.0,"Twilight (Twilight, #1)",en-US,3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439
3,226,John Green,2012.0,The Fault in Our Stars,eng,4.26,2346404,2478609,140739,47994,92723,327550,698471,1311871
4,210,Veronica Roth,2011.0,"Divergent (Divergent, #1)",eng,4.24,1903563,2216814,101023,36315,82870,310297,673028,1114304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,52,Mary Hoffman,2002.0,"City of Masks (Stravaganza, #1)",eng,3.90,12048,13385,555,314,758,3154,4872,4287
1350,22,Caragh M. O'Brien,2012.0,"Promised (Birthmarked, #3)",en-US,3.77,11766,12884,1260,256,1098,3565,4392,3573
1351,18,"Abigail Haas, Abby McDonald",2013.0,Dangerous Girls,eng,4.14,10439,12970,2631,203,553,2029,4567,5618
1352,19,Maria Dahvana Headley,2015.0,"Magonia (Magonia, #1)",eng,3.60,12510,13652,2910,577,1440,3881,4772,2982
1353,25,Simone Elkeles,2013.0,"Wild Cards (Wild Cards, #1)",eng,3.95,13954,15400,1514,406,965,3331,5038,5660

In [12]:
# Basic statistics
cleaned_ds.describe()

,books_count,original_publication_year,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
count,1153.000000,1153.000000,1153.000000,1.153000e+03,1.153000e+03,1153.000000,1153.000000,1153.000000,1153.00000,1.153000e+03,1.153000e+03
mean,52.777103,2003.698179,3.992819,1.014850e+05,1.097655e+05,5621.572420,2555.634866,5540.813530,19310.74935,3.383617e+04,4.852212e+04
std,64.054893,15.992755,0.223829,3.095194e+05,3.258908e+05,11410.001335,14830.209633,17529.393371,46821.01928,9.073628e+04,1.738494e+05
min,2.000000,1871.000000,3.230000,8.861000e+03,1.025100e+04,112.000000,33.000000,133.000000,946.00000,2.425000e+03,2.005000e+03
25%,24.000000,2003.000000,3.840000,1.858300e+04,2.030900e+04,1327.000000,330.000000,1041.000000,4333.00000,6.875000e+03,7.268000e+03
50%,38.000000,2008.000000,4.000000,3.139500e+04,3.398500e+04,2441.000000,688.000000,1884.000000,7170.00000,1.131900e+04,1.272500e+04
75%,61.000000,2011.000000,4.150000,6.682300e+04,7.233900e+04,4973.000000,1505.000000,3945.000000,14260.00000,2.517700e+04,2.841800e+04
max,1314.000000,2017.000000,4.740000,4.780653e+06,4.942365e+06,155254.000000,456191.000000,436802.000000,793319.00000,1.481305e+06,3.011543e+06

In [20]:
#Calculate total ratings count for each book
cleaned_ds['total_ratings'] = cleaned_ds['ratings_1'] + cleaned_ds['ratings_2'] + cleaned_ds['ratings_3'] + cleaned_ds['ratings_4'] + cleaned_ds['ratings_5']

# Sort the dataset by total ratings in descending order
most_selling_books = cleaned_ds[['title', 'total_ratings']].sort_values(by='total_ratings', ascending=False)

print("Top 5 most selling books within the Harry Potter series:")
print(most_selling_books.head(20))

C:\Users\win 10\AppData\Local\Temp\ipykernel_264\652562825.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_ds['total_ratings'] = cleaned_ds['ratings_1'] + cleaned_ds['ratings_2'] + cleaned_ds['ratings_3'] + cleaned_ds['ratings_4'] + cleaned_ds['ratings_5']

Top 5 most selling books within the Harry Potter series:
                                                title  total_ratings
0             The Hunger Games (The Hunger Games, #1)        4942365
1   Harry Potter and the Sorcerer's Stone (Harry P...        4800065
2                             Twilight (Twilight, #1)        3916824
3                              The Fault in Our Stars        2478609
4                           Divergent (Divergent, #1)        2216814
5                Catching Fire (The Hunger Games, #2)        1988079
6   Harry Potter and the Prisoner of Azkaban (Harr...        1969375
9   Harry Potter and the Chamber of Secrets (Harry...        1906199
7                   Mockingjay (The Hunger Games, #3)        1870748
10  Harry Potter and the Goblet of Fire (Harry Pot...        1868642
11  Harry Potter and the Deathly Hallows (Harry Po...        1847395
8   Harry Potter and the Order of the Phoenix (Har...        1840548
12  Harry Potter and the Half-Blood Prince (Harry ...        1785676
13  The Lion, the Witch, and the Wardrobe (Chronic...        1584884
14  The Lightning Thief (Percy Jackson and the Oly...        1411114
15                                     The Book Thief        1287798
17         City of Bones (The Mortal Instruments, #1)        1241799
16                            New Moon (Twilight, #2)        1199000
18                             Eclipse (Twilight, #3)        1176642
19                 Eragon (The Inheritance Cycle, #1)        1125231

In [21]:
# Calculate the average rating of the Harry Potter books
average_rating = cleaned_ds['average_rating'].mean()
print("\nAverage rating of the Harry Potter books:", average_rating)

Average rating of the Harry Potter books: 3.992818733738074